import '../../features/cards/domain/entities/payment_card.dart';

/// 12 sample cards seeded once on first launch so every feature
/// (list, detail, flip, copy, due-date, notes, mark-paid, reminders,
/// backup/restore) has realistic data to exercise.
///
/// Variety is intentional:
///  • Types — 8 Credit, 3 Debit, 1 Prepaid (covers all gradient themes)
///  • Networks — Visa / Mastercard / Amex (15-digit) / RuPay
///  • 8 carry a [dueDay] (reminders scheduled), 4 do not
///  • 7 carry [notes], 5 do not
const List<PaymentCard> kDemoCards = [
  PaymentCard(
    id: 'demo_01',
    holderName: 'Alex Joseph',
    cardNumber: '4539148803436467',
    expiryDate: '08/28',
    typeLabel: 'Credit',
    cvv: '742',
    bankName: 'HDFC Regalia',
    dueDay: 15,
    notes: 'Netbanking ID: alexj_hdfc\nCredit limit: ₹3,50,000\nReward points expire every Dec.',
  ),
  PaymentCard(
    id: 'demo_02',
    holderName: 'Alex Joseph',
    cardNumber: '5425233430109903',
    expiryDate: '03/27',
    typeLabel: 'Credit',
    cvv: '318',
    bankName: 'SBI SimplyCLICK',
    dueDay: 5,
    notes: 'Online spends 10X rewards.\nApp PIN hint: anniversary year.',
  ),
  PaymentCard(
    id: 'demo_03',
    holderName: 'Alex Joseph',
    cardNumber: '4000123456789010',
    expiryDate: '11/26',
    typeLabel: 'Debit',
    cvv: '561',
    bankName: 'ICICI Coral',
  ),
  PaymentCard(
    id: 'demo_04',
    holderName: 'Alex Joseph',
    cardNumber: '5105105105105100',
    expiryDate: '06/29',
    typeLabel: 'Credit',
    cvv: '904',
    bankName: 'Axis Magnus',
    dueDay: 21,
    notes: 'Concierge: 1800-419-0000\nUnlimited airport lounge access.',
  ),
  PaymentCard(
    id: 'demo_05',
    holderName: 'Alex Joseph',
    cardNumber: '378282246310005',
    expiryDate: '12/27',
    typeLabel: 'Credit',
    cvv: '1097',
    bankName: 'Amex Platinum',
    dueDay: 28,
    notes: 'Membership Rewards enrolled.\nFine Hotels & Resorts benefit active.',
  ),
  PaymentCard(
    id: 'demo_06',
    holderName: 'Alex Joseph',
    cardNumber: '6521987654321098',
    expiryDate: '04/28',
    typeLabel: 'Debit',
    cvv: '233',
    bankName: 'Kotak 811',
  ),
  PaymentCard(
    id: 'demo_07',
    holderName: 'Alex Joseph',
    cardNumber: '4716345678901234',
    expiryDate: '09/27',
    typeLabel: 'Credit',
    cvv: '655',
    bankName: 'IndusInd Legend',
    dueDay: 10,
  ),
  PaymentCard(
    id: 'demo_08',
    holderName: 'Alex Joseph',
    cardNumber: '5200828282828210',
    expiryDate: '01/27',
    typeLabel: 'Prepaid',
    cvv: '410',
    bankName: 'Yes Bank Gift',
    notes: 'Balance: ₹5,000\nNon-reloadable. Valid 1 year.',
  ),
  PaymentCard(
    id: 'demo_09',
    holderName: 'Alex Joseph',
    cardNumber: '4111111111111111',
    expiryDate: '05/29',
    typeLabel: 'Credit',
    cvv: '128',
    bankName: 'HSBC Cashback',
    dueDay: 2,
    notes: 'Login: alex.j\n1.5% unlimited cashback, auto-credited.',
  ),
  PaymentCard(
    id: 'demo_10',
    holderName: 'Alex Joseph',
    cardNumber: '5500000000000004',
    expiryDate: '07/28',
    typeLabel: 'Credit',
    cvv: '377',
    bankName: 'Citi Rewards',
    dueDay: 18,
  ),
  PaymentCard(
    id: 'demo_11',
    holderName: 'Alex Joseph',
    cardNumber: '6073123456789012',
    expiryDate: '02/27',
    typeLabel: 'Debit',
    cvv: '590',
    bankName: 'BoB Easy',
  ),
  PaymentCard(
    id: 'demo_12',
    holderName: 'Alex Joseph',
    cardNumber: '4263982640269299',
    expiryDate: '10/29',
    typeLabel: 'Credit',
    cvv: '813',
    bankName: 'StanChart Ultimate',
    dueDay: 25,
    notes: '3.33% reward rate on retail.\nPriority Pass enrolled.',
  ),
];
